import {env} from 'cloudflare:workers';import {isAdmin} from '../../../lib/admin';import {buildFilters} from '../../../lib/lead-filters';
const noStore={'Cache-Control':'no-store'};
export async function GET(req:Request){if(!await isAdmin())return Response.json({error:'Acesso restrito.'},{status:403,headers:noStore});const url=new URL(req.url);let filter;try{filter=buildFilters(url.searchParams);}catch(e:any){return Response.json({error:e.message},{status:400,headers:noStore});}const requested=Number(url.searchParams.get('page')||1);if(!Number.isInteger(requested)||requested<1||requested>100000)return Response.json({error:'Página inválida.'},{status:400});try{const db=(env as any).DB;const count=await db.prepare('SELECT COUNT(*) AS total FROM leads'+filter.where).bind(...filter.values).first();const total=Number(count.total);const pages=Math.max(1,Math.ceil(total/30));const page=Math.min(requested,pages);const rows=await db.prepare('SELECT id,name,phone,city,modality,answers,created_at,status,attended_at FROM leads'+filter.where+' ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?').bind(...filter.values,30,(page-1)*30).all();return Response.json({rows:rows.results,total,page,pages,snapshot:new Date().toISOString()},{headers:noStore});}catch{console.error('Failed to list leads');return Response.json({error:'Não foi possível carregar as solicitações. Tente novamente.'},{status:503,headers:noStore});}}
export async function PATCH(req:Request){if(!await isAdmin())return Response.json({error:'Acesso restrito.'},{status:403,headers:noStore});if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Origem inválida.'},{status:403});try{const b:any=await req.json();if(!b||typeof b.id!=='string'||!/^[-a-zA-Z0-9]{1,60}$/.test(b.id)||!['pendente','atendido'].includes(b.status))return Response.json({error:'Dados inválidos.'},{status:400});const result=await (env as any).DB.prepare('UPDATE leads SET status = ?, attended_at = ? WHERE id = ?').bind(b.status,b.status==='atendido'?new Date().toISOString():null,b.id).run();if(!result.meta.changes)return Response.json({error:'Solicitação não encontrada.'},{status:404});return Response.json({ok:true},{headers:noStore});}catch{console.error('Failed to update lead');return Response.json({error:'Não foi possível atualizar o atendimento.'},{status:503,headers:noStore});}}

export async function DELETE(req:Request){if(!await isAdmin())return Response.json({error:'Acesso restrito.'},{status:403,headers:noStore});if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Origem inválida.'},{status:403,headers:noStore});try{if(Number(req.headers.get('content-length')||0)>10000)return Response.json({error:'Dados inválidos.'},{status:400});const b:any=await req.json();if(!b||b.confirm!==true)return Response.json({error:'Confirme a exclusão.'},{status:400});const db=(env as any).DB;let result:any;
if(b.mode==='ids'){if(!Array.isArray(b.ids)||!b.ids.length||b.ids.length>30||b.ids.some((id:unknown)=>typeof id!=='string'||!/^[-a-zA-Z0-9]{1,60}$/.test(id)))return Response.json({error:'Seleção inválida.'},{status:400});const ids=[...new Set(b.ids)];result=await db.prepare('DELETE FROM leads WHERE id IN ('+ids.map(()=>'?').join(',')+')').bind(...ids).run();}
else if(b.mode==='filtered'){if(!Number.isInteger(b.expected)||b.expected<1||typeof b.snapshot!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(b.snapshot)||!Number.isFinite(Date.parse(b.snapshot))||Date.parse(b.snapshot)>Date.now()+5000)return Response.json({error:'Seleção inválida. Atualize a lista.'},{status:400});let filter;try{const params=new URLSearchParams();for(const k of ['status','modality','from','to']){const v=b.filters?.[k];if(v!==undefined&&typeof v!=='string')throw Error('Filtros inválidos.');if(v)params.set(k,v);}filter=buildFilters(params);}catch(e:any){return Response.json({error:e.message},{status:400});}const where=filter.where+(filter.where?' AND ':' WHERE ')+'created_at <= ?';const values=[...filter.values,b.snapshot];result=await db.prepare('DELETE FROM leads'+where+' AND (SELECT COUNT(*) FROM leads'+where+') = ?').bind(...values,...values,b.expected).run();if(!result.meta.changes)return Response.json({error:'A lista mudou. Atualize as solicitações e confirme novamente.'},{status:409,headers:noStore});}
else return Response.json({error:'Modo de exclusão inválido.'},{status:400});return Response.json({ok:true,deleted:Number(result.meta.changes||0)},{headers:noStore});
}catch{console.error('Failed to delete leads');return Response.json({error:'Não foi possível excluir. Tente novamente.'},{status:503,headers:noStore});}}
